name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to Raspberry Pi
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" . aviete@212.122.80.179:/home/aviete/projects/social

      - name: Build and run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no aviete@212.122.80.179 << 'EOF'
          cd /home/aviete/projects/social
          docker-compose down
          docker-compose up -d --build
          EOF
